export const CHANGE_CATEGORY="CHANGE_CATEGORY";
export const GET_CATEGORİES_SUCCESS ="GET_CATEGORİES_SUCCESS";
//magic string

export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS" ;
export const CREATE_PRODUCT_SUCCESS ="CREATE_PRODUCT_SUCCESS"; //EKLEME 
export const UPDATE_PRODUCT_SUCCESS ="UPDATE_PRODUCT_SUCCESS"; // GÜNCELLEME 

export const ADD_TO_CART ="ADD_TO_CART";
export const REMOVE_FROM_CART ="REMOVE_FROM_CART";